import {
  Box,
  Flex,
  Heading,
  Spacer,
  Button,
  Badge,
  Text,
} from "@chakra-ui/react";
import Head from "next/head";
import Link from "next/link";
import { Icon } from "@chakra-ui/react";
import { HiShoppingCart } from "react-icons/hi";

import { useAppState } from "state";

function Header({ title }) {
  const { state } = useAppState();

  const cartCount = state.cart.products?.length || 0;

  return (
    <Box w="100%" h="80px" backgroundColor="#0c4271">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Flex
        direction="row"
        alignItems="center"
        justifyContent="center"
        w="100%"
        pr={4}
        pl={4}
        h="100%"
      >
        <Heading color="#fff" size="md">
          {title}
        </Heading>
        <Spacer />
        <Link href="/cart">
          <Button backgroundColor="transparent" position="relative">
            <Icon as={HiShoppingCart} color="#fff" boxSize="2em" />
            <Badge
              ml="1"
              fontSize="0.8em"
              colorScheme="green"
              position="absolute"
              top="2px"
              left="10px"
              borderRadius="50%"
            >
              <Text>{cartCount}</Text>
            </Badge>
          </Button>
        </Link>
      </Flex>
    </Box>
  );
}

export default Header;
