import { Button } from "@chakra-ui/button";
import { Flex } from "@chakra-ui/layout";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex h="100vh" justifyContent="center" alignItems="center">
        <Button>
          <Link href="/products">فروشگاه</Link>
        </Button>
      </Flex>
    </div>
  );
}
